# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: "{{ include "charts.fullname" . }}-ingress-{{ .Values.env }}"
#   annotations:
#     kubernetes.io/ingress.class: alb
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: instance
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": {{ .Values.service.port }} }]'
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: "{{ include "charts.fullname" . }}-svc-{{ .Values.env }}"
#             port:
#               number: {{ .Values.service.port }}
