replicaCount: 3

env: develop

image:
  repository: 807230335956.dkr.ecr.us-east-1.amazonaws.com/ecr-repo-liatrio
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

accountNumber: 807230335956

serviceAccountRoleName: AmazonEKSLoadBalancerControllerRole

service:
  type: NodePort
  port: 443

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
