replicaCount: 3

env: prod

image:
  repository: 807230335956.dkr.ecr.us-east-1.amazonaws.com/ecr-repo-liatrio:latest
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

accountNumber: 807230335956

service:
  type: NodePort
  port: 80
  nodePort: 30000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
