name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Lint API
        run: cd api/ && npm run lint
      - name: Test API
        run: cd api/ && npm run test && npm run test:e2e
      - name: Build the Docker image
        run: cd api/ docker build .  --tag api:$(date +%s)
