name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint and Test
        run: cd api/
        run: npm ci
        run: npm run lint && npm run test && npm run test:e2e
      # - name: Build the Docker image
      #   run: cd api/ docker build .  --tag api:$(date +%s)
